import { execFile } from 'node:child_process'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { basename, join } from 'node:path'
import { promisify } from 'node:util'
import { pickUnityWorktreeTint } from '../../shared/unity-worktree-tint-palette'
import type { UnityWorktreeTint } from '../../shared/unity-worktree-tint-palette'

/**
 * Per-worktree colour identity inside the Unity editor (fork feature).
 *
 * Unity has no Chrome-profile-style project accent: its theme setting is
 * Light/Dark and the colour preferences are per USER, not per project. So the
 * identity is synthesised by a tiny generated editor script: the strip holding
 * the play controls is tinted, and the worktree name is prefixed to the window
 * title. Unity exposes no theming hook for that strip, so the tint is an inline
 * style set on the toolbar's UI Toolkit tree (inline always beats USS) — only
 * the internal window's type NAME is matched, no member reflection. Verified on
 * a real 6000.3.16f1 editor. Older editors fall back to a Scene view bar.
 *
 * Colour picking lives in `src/shared/unity-worktree-tint-palette.ts`: the
 * renderer's colour menu must predict the same colours this writer produces.
 *
 * Where it lands matters: `Assets/Private/` is already gitignored in the repos
 * this targets, so the script never shows up in `git status` and can't be
 * committed by accident. Anything under `Assets/` is compiled by Unity, which
 * is also why the generated code stays deliberately small and guards the newer
 * API behind a version define — a compile error here would break the user's
 * whole project, not just the tint.
 */

export { pickUnityWorktreeTint } from '../../shared/unity-worktree-tint-palette'
export type { UnityWorktreeTint } from '../../shared/unity-worktree-tint-palette'

const SCRIPT_DIR_RELPATH = join('Assets', 'Private', 'Editor')
const SCRIPT_RELPATH = join(SCRIPT_DIR_RELPATH, 'OrcaWorktreeTint.cs')
/** Unity writes one of these per script; removing the tint must take it too,
 *  or the editor logs an orphaned-meta warning on the next refresh. */
const SCRIPT_META_RELPATH = `${SCRIPT_RELPATH}.meta`

/**
 * Whether git ignores the script path in this worktree.
 *
 * The feature is on by default, so it must never be the reason a stray file
 * turns up in someone's `git status` — `Assets/Private/` happens to be ignored
 * in the repos this targets, but that is their choice, not a guarantee. A repo
 * that would track the file simply goes untinted.
 */
async function scriptPathIsGitIgnored(worktreePath: string): Promise<boolean> {
  try {
    // Exit 0 = ignored. `--no-index` so a path git already tracks still reports
    // its ignore rules rather than short-circuiting.
    await promisify(execFile)('git', ['check-ignore', '--quiet', '--no-index', SCRIPT_RELPATH], {
      cwd: worktreePath
    })
    return true
  } catch {
    return false
  }
}

/** C# string literal escaping for the one value we interpolate. */
function csharpString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function renderTintScript(label: string, tint: UnityWorktreeTint): string {
  const round = (value: number): string => value.toFixed(4)
  const name = csharpString(label)
  return `// <auto-generated>
// Generated by Orca — per-worktree Unity tint (${tint.name}).
// Lives in a gitignored folder; delete it or turn the toggle off to remove.
// </auto-generated>
#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
#if UNITY_6000_3_OR_NEWER
using UnityEngine.UIElements;
#endif

[InitializeOnLoad]
public class OrcaWorktreeTint
{
    private const string Label = "${name}";
    private const float BarHeight = 22f;
    private static readonly Color Tint =
        new Color(${round(tint.rgb.r)}f, ${round(tint.rgb.g)}f, ${round(tint.rgb.b)}f, 1f);
#if UNITY_6000_3_OR_NEWER
    private static readonly Color ToolbarTint =
        new Color(${round(tint.toolbarRgb.r)}f, ${round(tint.toolbarRgb.g)}f, ${round(tint.toolbarRgb.b)}f, 1f);
    private static double _nextToolbarPaint;
#endif

    static OrcaWorktreeTint()
    {
#if !UNITY_6000_3_OR_NEWER
        // No main-toolbar API on this editor: fall back to the Scene view.
        SceneView.duringSceneGui -= OnSceneGui;
        SceneView.duringSceneGui += OnSceneGui;
#endif
        EditorApplication.updateMainWindowTitle -= OnMainWindowTitle;
        EditorApplication.updateMainWindowTitle += OnMainWindowTitle;
        EditorApplication.UpdateMainWindowTitle();
#if UNITY_6000_3_OR_NEWER
        // The toolbar is an overlay canvas that rebuilds on its own schedule and
        // drops inline styles when it does, so the paint is re-applied on a slow
        // poll rather than once at load.
        EditorApplication.delayCall += PaintToolbar;
        EditorApplication.update -= RepaintToolbarPeriodically;
        EditorApplication.update += RepaintToolbarPeriodically;
#endif
    }

    private static void OnMainWindowTitle(ApplicationTitleDescriptor descriptor)
    {
        descriptor.title = Label + "  —  " + descriptor.title;
    }

#if UNITY_6000_3_OR_NEWER
    private static void RepaintToolbarPeriodically()
    {
        if (EditorApplication.timeSinceStartup < _nextToolbarPaint)
        {
            return;
        }
        _nextToolbarPaint = EditorApplication.timeSinceStartup + 3.0;
        PaintToolbar();
    }

    /**
     * Tints the strip that holds the play controls.
     *
     * Unity exposes no theming hook for it, so the paint walks to the UI Toolkit
     * panel that hosts the (internal) main-toolbar window and sets an inline
     * background — inline always beats USS. Only the window's type NAME is
     * matched; no member reflection. Everything is guarded because these class
     * names are new in 6.3: if the layout changes, the query simply finds
     * nothing and the toolbar keeps its default colour.
     */
    private static void PaintToolbar()
    {
        try
        {
            EditorWindow[] windows = Resources.FindObjectsOfTypeAll<EditorWindow>();
            foreach (EditorWindow window in windows)
            {
                if (window == null || window.GetType().FullName != "UnityEditor.MainToolbarWindow")
                {
                    continue;
                }
                VisualElement element = window.rootVisualElement;
                if (element == null)
                {
                    continue;
                }
                while (element.parent != null)
                {
                    element = element.parent;
                }
                element.Query(className: "unity-editor-main-toolbar").ForEach(found =>
                    found.style.backgroundColor = ToolbarTint);
                // The zones paint their own opaque boxes on top; clear them so the tint shows.
                element.Query(className: "unity-editor-toolbar-container").ForEach(found =>
                    found.style.backgroundColor = Color.clear);
                element.Query(className: "unity-editor-toolbar-container__zone").ForEach(found =>
                    found.style.backgroundColor = Color.clear);
            }
        }
        catch
        {
            // A future editor may reshape this entirely — never break the project over a tint.
        }
    }

#else
    private static void OnSceneGui(SceneView sceneView)
    {
        Handles.BeginGUI();
        Rect bar = new Rect(0f, 0f, sceneView.position.width, BarHeight);
        EditorGUI.DrawRect(bar, Tint);
        GUIStyle style = new GUIStyle(EditorStyles.boldLabel);
        style.normal.textColor = Color.black;
        style.alignment = TextAnchor.MiddleCenter;
        GUI.Label(bar, Label, style);
        Handles.EndGUI();
    }
#endif
}
#endif
`
}

/**
 * Writes (or removes) the tint script for one worktree.
 *
 * Idempotent on purpose: it is called on every seed and every Orca-launched
 * open, so an unchanged file must not be rewritten — a rewrite would make
 * Unity reimport the script and trigger a domain reload mid-session.
 */
export async function syncUnityWorktreeTint(args: {
  worktreePath: string
  enabled: boolean
  /** Defaults to the worktree folder name — what the sidebar row shows. */
  label?: string
  /** Every worktree folder name in the repo, so colours can avoid colliding. */
  siblingLabels?: readonly string[]
  /** Manual colour choices (label → hex) from the worktree context menu. */
  overridesByLabel?: Readonly<Record<string, string>>
}): Promise<'written' | 'removed' | 'unchanged' | 'skipped'> {
  const scriptPath = join(args.worktreePath, SCRIPT_RELPATH)
  if (!args.enabled) {
    let existed = false
    try {
      await readFile(scriptPath)
      existed = true
    } catch {
      // Nothing to remove.
    }
    if (!existed) {
      return 'unchanged'
    }
    await rm(scriptPath, { force: true })
    await rm(join(args.worktreePath, SCRIPT_META_RELPATH), { force: true })
    return 'removed'
  }
  if (!(await scriptPathIsGitIgnored(args.worktreePath))) {
    return 'skipped'
  }
  const label = args.label ?? basename(args.worktreePath)
  const contents = renderTintScript(
    label,
    pickUnityWorktreeTint(label, args.siblingLabels, args.overridesByLabel)
  )
  try {
    if ((await readFile(scriptPath, 'utf-8')) === contents) {
      return 'unchanged'
    }
  } catch {
    // Absent or unreadable — write it below.
  }
  await mkdir(join(args.worktreePath, SCRIPT_DIR_RELPATH), { recursive: true })
  await writeFile(scriptPath, contents, 'utf-8')
  return 'written'
}
